### ISSUE TITLE
Make it work with Star Citizen ?

### ISSUE THREAD

**Issue by hervedumoulinarc** [qian256/HoloLensArucoUnity#1]
I love Star Citizen and Im in my way of looking for a good headtracking tool with HoloLens...
Seem I found one.
I already installed HololensArucoUnity on my HoloLens, when I lauch It I have two Windows and text written " Markers : 0"
From here I followed the steps but I must admit It's difficult for me because I don't really understand what is It for... and if It Will really meet my needs for Star Citizen.
Coule you Give me some kind of help of any genre

**Comment by qian256** [comment]
Hi,

If your purpose is to track user's head (in world coordinates), the suggestion is:
1. Modify the aruco wrapper to open access to the detailed tracking information of each marker: for each marker, there is a Rodriguez vector representing rotation, and a translation vector (opencv Rvec, Tvec).
2. Reconstruct the pose of camera with respect to marker by combining Rvec and Tvec.
3. Step 2 can be done at every frame, but it is slow. Update it every few frames or in parallel.

The purpose of current implementation of HoloLensArucoUnity is to demonstrate the integration of aruco and opencv for uwp platform. The visualization is not awesome yet. That's why currently it is only showing the number of markers and ids of them.

**Comment by hervedumoulinarc** [comment]
Thanks.
Eventually do you have a room or Group on Slack, Telegram or Github where we could have a chat someday.
Im not sure I could do this alone.

Envoyé de mon téléphone Windows 10

De : Long Qian<mailto:notifications@github.com>
Envoyé le :mercredi 30 novembre 2016 15:29
À : qian256/HoloLensArucoUnity<mailto:HoloLensArucoUnity@noreply.github.com>
Cc : hervedumoulinarc<mailto:herve.dumoulin@outlook.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [qian256/HoloLensArucoUnity] Make it work with Star Citizen ? (#1)


Hi,

If your purpose is to track user's head (in world coordinates), the suggestion is:

  1.  Modify the aruco wrapper to open access to the detailed tracking information of each marker: for each marker, there is a Rodriguez vector representing rotation, and a translation vector (opencv Rvec, Tvec).
  2.  Reconstruct the pose of camera with respect to marker by combining Rvec and Tvec.
  3.  Step 2 can be done at every frame, but it is slow. Update it every few frames or in parallel.

The purpose of current implementation of HoloLensArucoUnity is to demonstrate the integration of aruco and opencv for uwp platform. The visualization is not awesome yet. That's why currently it is only showing the number of markers and ids of them.

-

**Comment by qian256** [comment]
Not yet, but I am absolutely willing to help

**Comment by hervedumoulinarc** [comment]
Hi How are you ?
Thanks for your help.
I have errors when I try buiding CMake for UWP with CMake 3,7...

<img width="960" alt="screenshot_4" src="https://cloud.githubusercontent.com/assets/13695640/20828801/7caccd6c-b879-11e6-85ca-91f8f88b3148.png">


In the readme it say "...set an environment variable..." but maybe it's for openCV...

![capture d ecran 249](https://cloud.githubusercontent.com/assets/13695640/20828893/f523dba0-b879-11e6-9999-509391b0c9db.png)

**Comment by qian256** [comment]
Have you installed the build tools of VS2015?
I found this post that might be helpful for you: http://stackoverflow.com/questions/31619296/cmake-does-not-find-visual-c-compiler

**Comment by hervedumoulinarc** [comment]
Thanks you, Qian, That was good help.
If you willing to help me a bit more, now I have difficulty to finish building CMake for UWP.

<img width="960" alt="screenshot_4" src="https://cloud.githubusercontent.com/assets/13695640/20845744/c238ad0e-b8c6-11e6-9006-9ccb03f40fc6.png">

**Comment by hervedumoulinarc** [comment]
Hi,
Im still working on my project.
Concerning the precedent error, I managed to passthrough, I don't need to rebuild CMake as all the support for UWPs has been part of CMake releases for a while now.
The next step is to build Opencv Binaries...
What does it means : 
![image](https://cloud.githubusercontent.com/assets/13695640/20966282/cbfbddd2-bc79-11e6-93e6-fb368747a8d2.png)
It is part of opencv "set an environment variable" readme.
Im going very slowly, but I hope it will work at the final, What do you think ?
I have Sunday night as deadline for this demo, I want to show it for my birthday... :)

**Comment by qian256** [comment]
Thanks for updating. It's good to know that the current release supports UWP already.
It seems that it is trying to build test and perf binaries of opencv, which are not necessary for HoloLens applications. Wish you good luck and happy birthday!

**Comment by hervedumoulinarc** [comment]
Thanks !
I have another little question.
You wrote
![image](https://cloud.githubusercontent.com/assets/13695640/20991045/66d17e9a-bcdc-11e6-94e1-3174a7d777b3.png)
How could I do this ?

**Comment by hervedumoulinarc** [comment]
Also should I build opencv with CMake or VSstudio 2015 ?

**Comment by qian256** [comment]
You can google search Aruco marker generator to generate a marker then simply print it. For opencv, you should generate the vs2015 solution of it using cmake, then build the actual binary using vs2015.

**Comment by hervedumoulinarc** [comment]
Thanks a lot, how many markers do I need for my project of headtracking ? 4 for each angle of the screen ?
On hololens there are two screens appearind in Hologram, it's disturbing, is it normal ?
When you say "Modify the aruco wrapper to open access to the detailed tracking information of each marker" Do I need coding skill !
Again Thanks a lot Qian ..

**Comment by qian256** [comment]
Only one marker is fine. Currently, the two screens are the effect. The original capture is displayed on the lest, the processed image is displayed on the right. The processed image shows the tracking result.
If you want to use the tracking result for advanced visualization, like some virtual object in the scene, you have to code a little bit!

**Comment by hervedumoulinarc** [comment]
Ok understand, I can see Something displaying in yellow on the marker in the right picture, but it's very small... I cannot describe What Im seeing What is the meaning of this information ? do I need it ?
Thanks !

**Comment by hervedumoulinarc** [comment]
<img width="954" alt="screenshot_4" src="https://cloud.githubusercontent.com/assets/13695640/21049320/795d6a5e-be14-11e6-8f34-88a3eaf91c43.png">
Uhh :( I get this when trying generating aruco with cmake, seems not very compelling but Im stuck for the moment...

**Comment by loowee2k5** [comment]
Hey HerveyDuMoulinarc ! I am a long term SC pledger and Ive been looking for a month to find a reliable streamer for star citizen to my Hololens. The remote desktop app just isnt fast enough, adding to the game's lag, it's a nightmare. Did you manage to get any decent stream going ? The head tracking would certainly make it even better !! Thx
